### ISSUE TITLE
How does one acquire dsdgen

### ISSUE THREAD

**Issue by hansbogert** [databricks/spark-sql-perf#12]
I've downloaded the TPC-DS package, from tpc.org. However it does not contain anything remotely resembling dsdgen.

**Comment by yhuai** [comment]
@hansbogert There should be dir called `tools`. You need to build `dsdgen`. I recommend to use https://github.com/gregrahn/tpcds-kit, which fixed a few issues of the original tool.

**Comment by hansbogert** [comment]
hmm i see that the DS benchmark has recently been updated. It seems the distribution is simply missing the tools dir.

> $ ll
total 732K
drwxr-xr-x 6 vdbogert vdbogert 4.0K Sep  2 02:53 DSGen
-rw-r--r-- 1 vdbogert vdbogert 724K Sep  7 10:17 dstools.zip
drwxrwxr-x 3 vdbogert vdbogert 4.0K Sep  3 21:01 __MACOSX

> $ ll DSGen
total 36K
drwxr-xr-x 2 vdbogert vdbogert 4.0K Aug 28 21:06 answer_sets
-rwxr-xr-x 1 vdbogert vdbogert  17K Aug 28 21:06 EULA.txt
drwxr-xr-x 2 vdbogert vdbogert 4.0K Aug 28 21:06 query_templates
drwxr-xr-x 2 vdbogert vdbogert 4.0K Aug 28 21:06 query_variants
drwxr-xr-x 2 vdbogert vdbogert 4.0K Aug 28 21:06 tests

Ill try @gregrahn's version then.

**Comment by yhuai** [comment]
Looks like `dstools` is the dir?

**Comment by hansbogert** [comment]
Thats a zipfile which i got from TPC, it holds the rest of the directoriee shown in the listing, but not a tools directory.

**Comment by yhuai** [comment]
o i see. Definitely give https://github.com/gregrahn/tpcds-kit a try. It should work.

**Comment by yhuai** [comment]
I am closing this issue.
