### ISSUE TITLE
Run TPC-H

### ISSUE THREAD

**Issue by hahasdnu1029** [databricks/spark-sql-perf#133]
Hi @juliuszsompolski 
Can you add steps on how to use TPC - h testing? Some experiments still require TPC - h testing

**Comment by juliuszsompolski** [comment]
cc @npoggi

**Comment by npoggi** [comment]
@hahasdnu1029 I will be uploading some TPCH data generator scripts next week

**Comment by npoggi** [comment]
@hahasdnu1029 take a look at the PR https://github.com/databricks/spark-sql-perf/pull/136
