### ISSUE TITLE
Can we put all working queries into this test kit? There are 86 out of 99 working in Spark 1.5

### ISSUE THREAD

**Issue by jfchen** [databricks/spark-sql-perf#23]
The IBM Spark Technology Center has made 86 (out of 99 TPCDS business queries) to run successfully on Spark 1.4.1 and 1.5.0. The existing spark-sql-perf test kit (on github from databricks) has a small subset of these. Could we add all the following queries into the kit so the community can learn/leverage?

query01
query02
query03
query04
query05
query07
query08
query09
query11
query12
query13
query15
query16
query17
query20
query21
query22
query24a
query24b
query25
query26
query27
query28
query29
query30
query31
query32
query33
query34
query36
query37
query38
query39a
query39b
query40
query42
query43
query45
query46
query47
query48
query49
query50
query51
query52
query53
query56
query57
query58
query59
query60
query61
query62
query63
query66
query67
query68
query69
query72
query73
query74
query75
query76
query77
query78
query79
query80
query81
query82
query83
query84
query85
query86
query87
query88
query89
query90
query91
query92
query93
query94
query95
query96
query97
query98
query99

Please contact me for the working queries.
Jesse Chen
jfchen@us.ibm.com

**Comment by marmbrus** [comment]
It would be great to add these.  I think the biggest barrier here is going to be adapting the data generation code to produce all of the fact tables.  Right now, we use the streaming mode of `dsdgen` and I don't think you can do this for the tables that have foreign key dependencies.

**Comment by jfchen** [comment]
What do you think about de-coupling dsdgen from the test kit itself, and
simply provide instructions on how to run dsdgen by itself?

Is it correct to assume that most users are probably using Hive and have
created these tables and loaded data already?

For our tests, we used externally generated data on HDFS (path passed in),
created DF and used csv to load data, like this:

  def importTable(sqlContext: SQLContext, filename: String, schema:
StructType, tablename: String) {
        val df = sqlContext.read.format("com.databricks.spark.csv").
        schema(schema).option("delimiter", "|").load(filename)
        df.registerTempTable(tablename)
   }

A few queries do have modifications -- thought to mention that but should
be good enough for this kit.

Will package the queries up and send it soon.

**Comment by marmbrus** [comment]
We don't necessarily need to block adding the queries on adding the data generation, but in my experience generating larger scale factors (SF1500 - SF15000) is actually a significant challenge.  So I would defiantly like to add support for generating them in the context of a Spark job.

**Comment by jfchen** [comment]
Definitely nice to have data generation done in a Spark job. What the best way to upload a gzip file containing all 86 queries in text files?

**Comment by marmbrus** [comment]
I wouldn't upload them as a zip file.  I'd do one of the following:
 - Add the files in `src/main/resources/...` and create a harness that reads them from the classloader and creates query objects for each.  Put this as another trait in the tpcds directory.
 - Hard code them as strings as we have in the other [tpcds files](https://github.com/databricks/spark-sql-perf/blob/master/src/main/scala/com/databricks/spark/sql/perf/tpcds/ImpalaKitQueries.scala)

**Comment by ecesena** [comment]
Do you have any update in this? I'd be interested in testing out the new queries... Thanks! E.

**Comment by jfchen** [comment]
This is still being worked on. Stay tuned please. We will implement this as first option from Michael's comment above - that makes sense.

**Comment by ecesena** [comment]
News? :) I may have some free time in the next days, if you could PR the queries I can have a look at how to add some scala glue... thanks!

**Comment by ecesena** [comment]
Great job!
