### ISSUE TITLE
 Not support partitionTables option

### ISSUE THREAD

**Issue by djvulee** [databricks/spark-sql-perf#26]
I used this  * tables.genData(location, format, true, true, true, true, true)* and occurred the following problem, it is ok for *tables.genData(location, format, true, false, true, true, true)*, so this benchmark do not support partitionTables?

**java.lang.RuntimeException: [7.1] failure: ``union'' expected but identifier DISTRIBUTE found**

After I read the source code, I found the problem occurred on this line. 
val query =
            s"""
              |SELECT
              |  $columnString
              |FROM
              |  $tempTableName
              |$predicates
              |DISTRIBUTE BY
              |  $partitionColumnString
            """.stripMargin

Is there any suggestion to solve this problem? 

I run this on Spark1.5.

**Comment by djvulee** [comment]
I am not familiar with Spark SQL, In my experiment, it seem that Spark SQL can not support DROP command.

If I use the **tpcds.createResultsTable()**, there will a error occurred similar to the above.

**Comment by marmbrus** [comment]
you need to use a HiveContext.

**Comment by djvulee** [comment]
Thanks! Because I do not find the difference  in the document at first.
