### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by xinglin** [databricks/spark-sql-perf#39]
Hi,

I am new to sbt and do not know how to use this package. I downloaded the zip file and unzip it. when i run 'sbt assembly' or 'sbt package', it is requiring to set DBC_USERNAME. Do we have to have Databrick Cloud account, in order to use this package? Could you provide some detail instructions on how to use this package? Thanks a lot!

-Xing

**Comment by marmbrus** [comment]
You shouldn't need them to compile.  The easiest thing would probably be to just set them to empty values, though I'd welcome a PR that removed this requirement.

**Comment by xinglin** [comment]
@marmbrus: thanks. I just commented out all these related lines and seem to compile now. After compiling it, I need to copy the jar file to ./lib in spark installation and I can run spark-shell, to do the test, is that right?

**Comment by marmbrus** [comment]
You can also use `--jars`.

**Comment by xinglin** [comment]
Thanks. I do not understand what these parameters mean in createExternalTables() and genData(). Could you also provide an example of createExternalTables() and genData(), assuming we want to run spark on HDFS?

**Comment by hchawla1** [comment]
Where should I set DBC_USERNAME to empty values?
