### ISSUE TITLE
Running on Spark 2.0 /Yarn

### ISSUE THREAD

**Issue by kgebaly** [databricks/spark-sql-perf#64]
I get an error trying to import class Tables from target/scala-2.10/spark-sql-perf_2.10-0.4.7-SNAPSHOT.jar 
I use $spark-shell --jars ...
```scala> import com.databricks.spark.sql.perf.tpcds.Tables
<console>:23: error: object databricks is not a member of package com```
I also noticed:
`WARN yarn.Client: Neither spark.yarn.jars nor spark.yarn.archive is set, falling back to uploading libraries under SPARK_HOME.`

Any pointers?

**Comment by hchawla1** [comment]
Is your jar file included in your classpath or pointed out in conf file?
Like: spark.driver.extraClassPath or spark.executor.extraClassPath
http://spark.apache.org/docs/latest/configuration.html

**Comment by kgebaly** [comment]
spark.driver.extraClassPath works fine.
Thank you.
