### ISSUE TITLE
Spark session getting crashed when running val tpcds = new TPCDS (sqlContext = sqlContext) in spark 2.0.0 preview

### ISSUE THREAD

**Issue by sridharpothamsetti** [databricks/spark-sql-perf#70]
Hi, 

1)I have created the jar file of spark-sql-perf after building it and started spark-shell with that jar.

2) When I am running below commands in spark 2.0.0 preview spark shell
import com.databricks.spark.sql.perf.tpcds.Tables
val tables = new Tables(sqlContext, "/root/tpcds-kit-master/dsdgen/tools/", 2)
tables.genData("hdfs://192.168.126.128:8020/tmp/temp1", "parquet", true, true, true, true, true)
tables.createExternalTables("hdfs://192.168.126.128:8020/tmp/temp1", "parquet", "sparkperf", true)
import com.databricks.spark.sql.perf.tpcds.TPCDS
val tpcds = new TPCDS (sqlContext = sqlContext)   **This command is causing issue in spark 2.0.0. preview**.

Please find the error details in the attached file
[spark shell command error.txt](https://github.com/databricks/spark-sql-perf/files/329352/spark.shell.command.error.txt)

Please let me know if any further information required.

**Comment by hchawla1** [comment]
which branch/version of sparl sql you are using? I suspect it's old one..

**Comment by sridharpothamsetti** [comment]
I am using below versions
1) the latest version of spark-2.0.0-preview-bin-hadoop2.7 /scala 2.11.8  and spark-sql will be of same version only.
2) And the spark-sql-perf is compiled to a jar with the given build.sbt.
 Please let me know if you want me to share any details.

**Comment by sridharpothamsetti** [comment]
I tried again with new HDP VM and it worked fine with spark 2.0.0 preview hadoop 2.7 and scala 2.11.8. I am able to run the commands perfectly.  The issue related to val tpcds = new TPCDS (sqlContext = sqlContext) is resolved with new VM. May be its due to environment issue.
