### ISSUE TITLE
cant gen data

### ISSUE THREAD

**Issue by lordk911** [databricks/spark-sql-perf#83]
I met error : 
Caused by: java.lang.RuntimeException: Could not find dsdgen at /home/dcos/tpcds-kit-master/tools/dsdgen or //home/dcos/tpcds-kit-master/tools/dsdgen. Run install

I have run 'make' under /home/dcos/tpcds-kit-master/tools/
my scala code is : 
val tables = new Tables(sqlContext, "/home/dcos/tpcds-kit-master/tools", 1) tables.genData("hdfs://master1:9000/tpctest", "parquet", true, false, false, false, false)

**Comment by Winemusic** [comment]
I have the same problem.

**Comment by lordk911** [comment]
cp 'tpcds-kit' to all the work nodes into same folder

**Comment by Winemusic** [comment]
Thanks,the problem was solved.





At 2016-07-28 04:41:44, "kai.shen" <notifications@github.com> wrote:


cp 'tpcds-kit' to all the work nodes into same folder
